version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      okio:
        patterns:
          - "com.squareup.okio:*"
      okhttp:
        patterns:
          - "com.squareup.okhttp3:*"
      moshi:
        patterns:
          - "com.squareup.moshi:*"
      coroutines:
        patterns:
          - "org.jetbrains.kotlinx:kotlinx-coroutines*"
      retrofit:
        patterns:
          - "com.squareup.retrofit2:*"
  - package-ecosystem: "gradle"
    directory: "/examples/example-project/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/.github/scripts/"
    schedule:
      interval: "weekly"
