= Gradle Enterprise API Kotlin

:lib-version: 0.16.0
:1: https://docs.gradle.com/enterprise/api-manual/
:2: https://square.github.io/retrofit/
:3: https://github.com/square/retrofit/issues/3448
:4: https://github.com/square/retrofit/issues/3144#issuecomment-508300518
:5: https://docs.gradle.com/enterprise/api-manual/ref/2022.4.html
:6: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/README.adoc
:7: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/
:8: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-config/index.html
:9: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-gradle-enterprise-api/
:11: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-gradle-enterprise-api/shutdown.html
:12: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-config/-cache-config/cache-enabled.html
:13: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-config/-cache-config/index.html
:14: https://jitpack.io/#gabrielfeo/gradle-enterprise-api-kotlin
:16: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-config/api-url.html
:17: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-config/api-token.html
:18: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-builds-api/index.html
:19: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api.model/-gradle-attributes/index.html
:20: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-builds-api/index.html
:21: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-builds-api/get-builds.html
:22: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-builds-api/get-gradle-attributes.html
:23: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-gradle-enterprise-api/-default-instance/index.html
:24: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api.extension/get-gradle-attributes-flow.html
:25: https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api.extension/index.html
:26: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/

image:https://jitpack.io/v/gabrielfeo/gradle-enterprise-api-kotlin.svg[link="{14}"]
image:https://img.shields.io/badge/javadoc-latest-orange[link="{7}"]

A Kotlin library to access the link:{1}[Gradle Enterprise API], easy to use from Kotlin scripts, projects or Jupyter notebooks:

[source,kotlin]
----
GradleEnterpriseApi.buildsApi.getBuilds(since = yesterdayMilli).forEach {
  println(it)
}
----

== Setup

Set up once and use the library from anywhere in your machine:

* link:{16}[`GRADLE_ENTERPRISE_API_URL`] environment variable: the URL of your Gradle Enterprise instance
* link:{17}[`GRADLE_ENTERPRISE_API_TOKEN`] environment variable: an API access token for the Gradle Enterprise instance.
** Or a macOS keychain entry labeled `gradle-enterprise-api-token` (recommended).

That's it! You can now use the library without any code configuration from:

* link:./examples/example-script.main.kts[Kotlin scripts (`kts`)]
* link:./examples/example-project[Kotlin projects]
* link:./examples/example-notebooks[Jupyter notebooks with the Kotlin kernel]

=== Setup snippets

.Add to a Kotlin script
[source,kotlin,subs="attributes"]
----
@file:Repository("https://jitpack.io")
@file:DependsOn("com.github.gabrielfeo:gradle-enterprise-api-kotlin:{lib-version}")
----

.Add to a Kotlin project
.Groovy
[source,groovy,subs="attributes"]
----
repositories {
  maven { url = 'https://jitpack.io' }
}
dependencies {
  implementation 'com.github.gabrielfeo:gradle-enterprise-api-kotlin:{lib-version}'
}
----
.Kotlin
[source,kotlin,subs="attributes"]
----
repositories {
  maven(url = "https://jitpack.io")
}
dependencies {
  implementation("com.github.gabrielfeo:gradle-enterprise-api-kotlin:{lib-version}")
}
----

.Add to a Jupyter notebook
[source,subs="attributes"]
----
%useLatestDescriptors
%use gradle-enterprise-api-kotlin(version={lib-version})
----

== Usage

The link:{9}[`GradleEnterpriseApi`] interface represents the Gradle Enterprise REST API. It contains the 4 APIs exactly as listed in the link:{5}[REST API Manual]:

[source,kotlin]
----
interface GradleEnterpriseApi {
  val buildsApi: BuildsApi
  val buildCacheApi: BuildCacheApi
  val metaApi: MetaApi
  val testDistributionApi: TestDistributionApi
}
----

For example, link:{20}[`BuildsApi`] contains all endpoints under `/api/builds/`:

* link:{21}[`BuildsApi.getBuilds`]: `GET /api/builds`
* link:{22}[`BuildsApi.getGradleAttributes`]: `GET /api/builds/{id}/gradle-attributes`
* ...

=== Calling the APIs

For simple use cases, you may use the companion instance (link:{23}[DefaultInstance]) directly, as if calling static methods:

[source,kotlin]
----
GradleEnterpriseApi.buildsApi.getBuilds(since = yesterdayMilli)
----

It's recommended to call link:{11}[`GradleEnterpriseApi.shutdown()`] at the end of scripts to release resources and let the program exit.
Otherwise, it'll keep running for an extra ~60s after code finishes, as an link:{4}[expected behavior of OkHttp].

=== Caching

HTTP caching is available, which can speed up queries significantly, but is off by default.
Enable by simply setting link:{12}[`GRADLE_ENTERPRISE_API_CACHE_ENABLED`] to `true`.
See link:{13}[`CacheConfig`] for caveats.

=== Extensions

Explore the library's convenience extensions: link:{25}[`com.gabrielfeo.gradle.enterprise.api.extension`].

What you'll probably use the most is link:{24}[`getGradleAttributesFlow`], which will call `/api/builds` to get the list of build IDs since a given date and join each with `/api/builds/{id}/gradle-attributes`, which contains tags and custom values on each build.
It also takes care of paging under-the-hood, returning a link:{26}[`Flow`] of all builds since the given date, so you don't have to worry about the REST API's limit of 1000 builds per request:

[source,kotlin]
----
val builds = GradleEnterpriseApi.buildsApi.getGradleAttributesFlow(since = lastYear)
builds.collect {
  // ...
}
----

== Documentation

image:https://img.shields.io/badge/javadoc-latest-orange[link="{7}"]

The javadoc of API interfaces and models, such as link:{18}[`BuildsApi`] and link:{19}[`GradleAttributes`], matches the link:{5}[REST API Manual] exactly.
Both these classes and Gradle's own manual are generated from the same OpenAPI spec.

== Optional setup

Creating a custom link:{8}[`Config`] allows you to change library settings via code instead of environment variables.
It also lets you share resource between the library's `OkHttpClient` and your own.
For example:

[source,kotlin]
----
val config = Config(
  apiUrl = "https://ge.mycompany.com/api/",
  apiToken = { vault.getGeApiToken() },
  clientBuilder = existingClient.newBuilder(),
)
val api = GradleEnterpriseApi.newInstance(config)
api.buildsApi.getBuilds(since = yesterdayMilli)
----

See the link:{8}[`Config`] documentation for more.

== More info

* Currently built for Gradle Enterprise `2022.4`, but should work fine with previous and future versions. The library will be updated regularly for new API versions.
* Use JDK 8 or 14+ to run, if you want to avoid the "illegal reflective access" warning about link:{3}[Retrofit]
* All classes live in these packages. If you need to make small edits to scripts where there's no auto-complete, wildcard imports can be used:

[source,kotlin]
----
import com.gabrielfeo.gradle.enterprise.api.*
import com.gabrielfeo.gradle.enterprise.api.model.*
import com.gabrielfeo.gradle.enterprise.api.model.extension.*
----
