# yaml-language-server: $schema=./.reference/gradle-enterprise-config-schema-9.json

global:
  hostname: ge.example.com
  externalSSLTermination: true
  externalPort: 8180
  unattended:
    configuration:
      systemPassword: "password"

authenticationBroker:
  adminPassword:
    value: "superS3cret!"
  clientSecret:
    value: "superS3cret!"

ingress:
  enabled: true
  ssl:
    enabled: false
