name: 'Check for new API spec version'

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: false
  workflow_call:

defaults:
  run:
    shell: bash

env:
  DRY_RUN: ${{ github.event.inputs.dry_run || github.event_name == 'pull_request' }}

jobs:

  check-new-api-spec:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Update API spec version'
        run: ./.github/scripts/update_api_spec_version.py
      - name: 'Read current spec version'
        run: |
          version="$(./.github/scripts/read_current_api_spec_version.py)"
          [[ -n "$version" ]]
          echo "SPEC_VERSION=$version" | tee -a "$GITHUB_ENV"
      - name: 'Create PR'
        if: ${{ DRY_RUN == 'false' }}
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "feature/api-spec-${{ env.SPEC_VERSION }}"
          commit-message: "Bump GE API spec version to ${{ env.SPEC_VERSION }}"
          title: "Support Gradle Enterprise API ${{ env.SPEC_VERSION }}"
          body: "https://docs.gradle.com/enterprise/api-manual/#release_history"
          author: "github-actions <github-actions@github.com>"
          committer: "github-actions <github-actions@github.com>"
