name: 'Check for new API spec version'

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: false
  workflow_call:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: true

defaults:
  run:
    shell: bash

jobs:

  check-new-api-spec:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Update API spec version'
        run: |
          if ./.github/scripts/update_api_spec_version.py | tee new.txt; then
            echo "NEW_VERSION=$(cat new.txt)" >> $GITHUB_ENV
          fi
          rm new.txt || true
      - name: 'Create PR'
        if: ${{ !inputs.dry_run && env.NEW_VERSION }}
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "feature/api-spec-${{ env.NEW_VERSION }}"
          commit-message: "Bump GE API spec version to ${{ env.NEW_VERSION }}"
          title: "Bump GE API spec version to ${{ env.NEW_VERSION }}"
          body: "https://docs.gradle.com/enterprise/api-manual/#release_history"
          author: "github-actions <github-actions@github.com>"
          committer: "github-actions <github-actions@github.com>"
          add-paths: "gradle.properties"
