name: 'Check PR'

on:
  pull_request

defaults:
  run:
    shell: bash

jobs:

  kotlin-tests:
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_API_URL: "${{ vars.DEVELOCITY_API_URL }}"
      DEVELOCITY_API_TOKEN: "${{ secrets.DEVELOCITY_API_TOKEN }}"
      DEVELOCITY_API_CACHE_ENABLED: "false"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: gradle check
        uses: ./.github/actions/build
        with:
          args: check

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - run: pip install -r .github/scripts/requirements.txt
      - name: 'unittest discover'
        run: python3 -m unittest discover -bs .github/scripts

  readme-links-test:
    uses: ./.github/workflows/test-readme-links.yml

  dry-run-publish-javadoc:
    uses: ./.github/workflows/publish-javadoc.yml
    with:
      dry_run: true

  dry-run-publish-library:
    uses: ./.github/workflows/publish-library.yml
    with:
      dry_run: true

  dry-run-update-api-spec:
    uses: ./.github/workflows/update-api-spec.yml
    with:
      dry_run: true
