name: 'Check PR'

on:
  pull_request

defaults:
  run:
    shell: bash

jobs:

  kotlin-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for modified code
        id: diff
        uses: tj-actions/changed-files@v24
        with:
          files: |
            **/src/**
            **/*.gradle*
            ./gradle/*
      - name: gradle check
        if: ${{ steps.diff.outputs.all_modified_files }}
        uses: ./.github/actions/build
        with:
          tasks: 'check'
          # artifact-name: 'Test reports (${{matrix.runner}})'
          # path-to-upload: '**/build/reports/tests/**'

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for modified code
        id: diff
        uses: tj-actions/changed-files@v24
        with:
          files: |
            **/*.py
      - name: 'unittest discover'
        if: ${{ steps.diff.outputs.all_modified_files }}
        run: python3 -m unittest discover -bs .github/scripts

  choose-dry-runs:
    runs-on: ubuntu-latest
    outputs:
      dry-run-publish-javadoc: ${{ steps.diff-publish-javadoc.outputs.all_modified_files }}
      dry-run-check-new-api-spec: ${{ steps.diff-check-new-api-spec.outputs.all_modified_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Diff publish-javadoc.yml
        id: diff-publish-javadoc
        uses: tj-actions/changed-files@v24
        with:
          files: |
            .github/workflows/publish-javadoc.yml
            .github/scripts/*
            **/src/**
            **/*.gradle*
            ./gradle/*
      - name: Diff check-new-api-spec.yml
        id: diff-check-new-api-spec
        uses: tj-actions/changed-files@v24
        with:
          files: |
            .github/workflows/check-new-api-spec.yml
            .github/scripts/*

  dry-run-publish-javadoc:
    needs: [choose-dry-runs]
    if: ${{ needs.choose-dry-runs.outputs.dry-run-publish-javadoc }}
    uses: ./.github/workflows/publish-javadoc.yml
    with:
      dry_run: true

  dry-run-check-new-api-spec:
    needs: [choose-dry-runs]
    if: ${{ needs.choose-dry-runs.outputs.dry-run-check-new-api-spec }}
    uses: ./.github/workflows/check-new-api-spec.yml
    with:
      dry_run: true
