name: 'Publish library to Central'

on:
  push:
    tags: ['*']
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        default: false
  workflow_call:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_URL: "${{ vars.DEVELOCITY_URL }}"
      DEVELOCITY_ACCESS_KEY: "${{ secrets.DEVELOCITY_ACCESS_KEY }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Verify that version property matches tag
        if: ${{ inputs.dry_run != true }}
        run: grep -qP '^version=${{ github.ref_name }}$' gradle.properties
      - name: gradle publish
        uses: ./.github/actions/build
        with:
          dry-run: ${{ inputs.dry_run }}
          args: >-
            check
            publishDevelocityApiKotlinPublicationToMavenCentralRepository
            publishRelocationPublicationToMavenCentralRepository
            --rerun-tasks
            '-Pmaven.central.username=${{ secrets.MAVEN_CENTRAL_USERNAME }}'
            '-Pmaven.central.password=${{ secrets.MAVEN_CENTRAL_PASSWORD }}'
            '-Psigning.password=${{ secrets.GPG_PASSWORD }}'
            '-Psigning.secretKey=${{ secrets.GPG_SECRET_KEY }}'
          artifact-name: 'outputs'
          path-to-upload: |
            library/build/*-api.yaml
            library/build/post-processed-api/**/*
            library/build/publications/**/*
            library/build/libs/**/*
