name: 'Publish javadoc'

on:
  push:
    tags: ['*']
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: false
  pull_request:

defaults:
  run:
    shell: bash

env:
  DRY_RUN: ${{ github.event.inputs.dry_run || github.event_name == 'pull_request' }}
  JAR_NAME: gradle-enterprise-api-kotlin-SNAPSHOT-javadoc.jar

jobs:

  build-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build javadoc
        uses: ./.github/actions/build
        with:
          tasks: 'javadocJar'
          artifact-name: 'javadoc'
          path-to-upload: "build/libs/${{ env.JAR_NAME }}"

  commit-to-gh-pages:
    needs: [build-javadoc]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download javadoc
        uses: actions/download-artifact@v3
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          rm -rf docs
          unzip "$JAR_NAME" -d docs
          git add docs
          git commit -m "Add ${{ github.ref_name }} javadoc"
      - name: Push
        run: |
          if [[ "$DRY_RUN" == 'true' ]]; then
            args=' --dry-run'
          fi
          git push $args