name: 'Publish javadoc'

on:
  push:
    tags: ['*']
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: false
  workflow_call:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: true

defaults:
  run:
    shell: bash

env:
  JAR_NAME: gradle-enterprise-api-kotlin-SNAPSHOT-javadoc.jar

jobs:

  build-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build javadoc
        uses: ./.github/actions/build
        with:
          tasks: 'dokkaHtml'
          artifact-name: 'javadoc'
          path-to-upload: "build/dokka/html/**/*"

  test-readme-links:
    runs-on: ubuntu-latest
    needs: [build-javadoc]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download new javadoc
        uses: actions/download-artifact@v3
        with:
          path: 'build/dokka/html'
      - name: Replace javadoc links for local links
        run: ./.github/scripts/replace_readme_links.py && git diff
      - name: Check README links
        if: ${{ !inputs.dry_run }}
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: .
          max-depth: 1

  publish-javadoc:
    needs:
      - build-javadoc
      - test-readme-links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Delete current javadoc
        run: rm -rf docs
      - name: Download new javadoc
        uses: actions/download-artifact@v3
        with:
          path: docs
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit --allow-empty -m "Add ${{ github.ref_name }} javadoc"
      - name: Push
        run: |
          if [[ "${{ inputs.dry_run }}" == 'true' ]]; then
            args=' --dry-run'
          fi
          git push $args
