name: 'Submit dependencies'

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  submit-dependencies:
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Submit Gradle dependencies
        uses: gradle/actions/dependency-submission@v4
        env:
          DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: '.*[Tt]est(Compile|Runtime)Classpath'
