name: 'Submit dependencies'

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  submit-dependencies:
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Gradle
        uses: ./.github/actions/build
      - name: Submit Gradle dependencies
        uses: gradle/actions/gradle-dependency-submission@v3
        with:
          dependency-graph: 'generate-and-submit'
        env:
          DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: '.*[Tt]est(Compile|Runtime)Classpath'
