name: 'Submit dependencies'

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  submit-dependencies:
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Gradle
        uses: ./.github/actions/build
      - name: Submit Gradle dependencies
        uses: mikepenz/gradle-dependency-submission@v0.8.5
        with:
          use-gradlew: false
          include-build-environment: true
          gradle-build-configuration-mapping: |
            :|compileClasspath
            :|runtimeClasspath
